name: otp_feature
description: Automated verification and 2FA OTP code extraction and 1-click copy feature module for AndroMac
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  meta: ^1.15.0
  bridge_protocol: ^0.1.0
  bridge_core: ^0.1.0

dev_dependencies:
  test: ^1.25.0
