import Cocoa

/// Monitors the macOS NSPasteboard for changes, filters sensitive password manager items,
/// suppresses local loopback echoes, and dispatches text updates to Flutter.
public class PasteboardMonitor: NSObject {

    public static let shared = PasteboardMonitor()

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int = 0
    private var timer: Timer?
    private var onPasteboardChanged: ((String) -> Void)?

    // Password manager and transient pasteboard markers that must never be synced across devices
    private let sensitiveTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("com.agilebits.onepassword"),
        NSPasteboard.PasteboardType("de.petermaurer.TransientPasteboardType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    ]

    private override init() {
        super.init()
        self.lastChangeCount = pasteboard.changeCount
    }

    public func startMonitoring(callback: @escaping (String) -> Void) {
        self.onPasteboardChanged = callback
        self.lastChangeCount = pasteboard.changeCount

        timer?.invalidate()
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            self?.checkForChanges()
        }
    }

    public func stopMonitoring() {
        timer?.invalidate()
        timer = nil
    }

    private func checkForChanges() {
        let currentCount = pasteboard.changeCount
        guard currentCount != lastChangeCount else { return }
        lastChangeCount = currentCount

        // 1. Privacy filter: verify pasteboard does not contain password manager flags
        if isSensitiveContent() {
            return
        }

        // 2. Extract plain text content
        guard let text = pasteboard.string(forType: .string), !text.isEmpty else {
            return
        }

        onPasteboardChanged?(text)
    }

    /// Checks if any password manager concealed or transient types are present.
    private func isSensitiveContent() -> Bool {
        guard let availableTypes = pasteboard.types else { return false }
        for sensitive in sensitiveTypes {
            if availableTypes.contains(sensitive) {
                return true
            }
        }
        return false
    }

    /// Copies text into the macOS pasteboard while updating changeCount to prevent self-echo.
    public func copyToPasteboard(text: String) {
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        lastChangeCount = pasteboard.changeCount
    }

    public func readCurrentText() -> String? {
        if isSensitiveContent() { return nil }
        return pasteboard.string(forType: .string)
    }

    public func getChangeCount() -> Int {
        return pasteboard.changeCount
    }
}
