name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  analyze-and-test:
    name: Lint & Test Suite
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Check code formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Run Dart Analyzer
        run: dart analyze --fatal-infos

      - name: Run Package Tests
        run: dart test test/ $(find packages tools apps -name "*_test.dart")
